# db/seeds.rb
# ============================================================
# Fichier de seed de l'application Fouta Music
# ============================================================
# Ce fichier peuple la base de données avec les albums et pistes
# de la base Chinook (données musicales réelles).
#
# EXÉCUTION :
#   $ rails db:seed
#
# ATTENTION : Le seed peut prendre quelques secondes car il insère
# plusieurs centaines d'albums et de pistes musicales.
# ============================================================

# ----------------------------------------------------------
# NETTOYAGE : suppression de toutes les données existantes
# ----------------------------------------------------------
# Réinitialise les deux tables avant d'insérer les nouvelles données.
# L'ordre est important : supprimer les tracks avant les albums.
Album.destroy_all    # Supprime tous les albums de la BDD
Track.destroy_all    # Supprime toutes les pistes de la BDD
puts "==> Données existantes supprimées."

# ----------------------------------------------------------
# TABLEAU DES ALBUMS
# ----------------------------------------------------------
# Tableau Ruby contenant les hashes de tous les albums à insérer.
# Chaque hash représente un album avec ses attributs title et artist.
album_array = [
  {title:'For Those About To Rock We Salute You', artist:'AC/DC'},
  {title:'Balls to the Wall', artist:'Accept'},
  {title:'Restless and Wild', artist:'Accept'},
  {title:'Let There Be Rock', artist:'AC/DC'},
  {title:'Big Ones', artist:'Aerosmith'},
  {title:'Jagged Little Pill', artist:'Alanis Morissette'},
  {title:'Facelift', artist:'Alice In Chains'},
  {title:'Warner 25 Anos', artist:'Antônio Carlos Jobim'},
  {title:'Plays Metallica By Four Cellos', artist:'Apocalyptica'},
  {title:'Audioslave', artist:'Audioslave'},
  {title:'Out Of Exile', artist:'Audioslave'},
  {title:'BackBeat Soundtrack', artist:'BackBeat'},
  {title:'The Best Of Billy Cobham', artist:'Billy Cobham'},
  {title:'Alcohol Fueled Brewtality Live! [Disc 1]', artist:'Black Label Society'},
  {title:'Alcohol Fueled Brewtality Live! [Disc 2]', artist:'Black Label Society'},
  {title:'Black Sabbath', artist:'Black Sabbath'},
  {title:'Black Sabbath Vol. 4 (Remaster)', artist:'Black Sabbath'},
  {title:'Body Count', artist:'Body Count'},
  {title:'Chemical Wedding', artist:'Bruce Dickinson'},
  {title:'The Best Of Buddy Guy - The Millenium Collection', artist:'Buddy Guy'},
  {title:'Prenda Minha', artist:'Caetano Veloso'},
  {title:'Sozinho Remix Ao Vivo', artist:'Caetano Veloso'},
  {title:'Minha Historia', artist:'Chico Buarque'},
  {title:'Afrociberdelia', artist:'Chico Science & Nação Zumbi'},
  {title:'Da Lama Ao Caos', artist:'Chico Science & Nação Zumbi'},
  {title:'Acústico MTV [Live]', artist:'Cidade Negra'},
  {title:'Cidade Negra - Hits', artist:'Cidade Negra'},
  {title:'Na Pista', artist:'Cláudio Zoli'},
  {title:'Axé Bahia 2001', artist:'Various Artists'},
  {title:'BBC Sessions [Disc 1] [Live]', artist:'Led Zeppelin'},
  {title:'Bongo Fury', artist:'Frank Zappa & Captain Beefheart'},
  {title:'Carnaval 2001', artist:'Various Artists'},
  {title:'Chill: Brazil (Disc 1)', artist:'Marcos Valle'},
  {title:'Chill: Brazil (Disc 2)', artist:'Antônio Carlos Jobim'},
  {title:'Garage Inc. (Disc 1)', artist:'Metallica'},
  {title:'Greatest Hits II', artist:'Queen'},
  {title:'Greatest Kiss', artist:'Kiss'},
  {title:'Heart of the Night', artist:'Spyro Gyra'},
  {title:'International Superhits', artist:'Green Day'},
  {title:'Into The Light', artist:'David Coverdale'},
  {title:'Meus Momentos', artist:'Gonzaguinha'},
  {title:'Minha História', artist:'Os Mutantes'},
  {title:'MK III The Final Concerts [Disc 1]', artist:'Deep Purple'},
  {title:'Physical Graffiti [Disc 1]', artist:'Led Zeppelin'},
  {title:'Sambas De Enredo 2001', artist:'Various Artists'},
  {title:'Supernatural', artist:'Santana'},
  {title:'The Best of Ed Motta', artist:'Ed Motta'},
  {title:'The Essential Miles Davis [Disc 1]', artist:'Miles Davis'},
  {title:'The Essential Miles Davis [Disc 2]', artist:'Miles Davis'},
  {title:'The Final Concerts (Disc 2)', artist:'Deep Purple'},
  {title:'Up An Atom', artist:'Gene Krupa'},
  {title:'Vinícius De Moraes - Sem Limite', artist:'Toquinho & Vinícius'},
  {title:'Vozes do MPB', artist:'Various Artists'},
  {title:'Chronicle, Vol. 1', artist:'Creedence Clearwater Revival'},
  {title:'Chronicle, Vol. 2', artist:'Creedence Clearwater Revival'},
  {title:'Cássia Eller - Coleção Sem Limite [Disc 2]', artist:'Cássia Eller'},
  {title:'Cássia Eller - Sem Limite [Disc 1]', artist:'Cássia Eller'},
  {title:'Come Taste The Band', artist:'Deep Purple'},
  {title:'Deep Purple In Rock', artist:'Deep Purple'},
  {title:'Fireball', artist:'Deep Purple'},
  {title:'Knocking at Your Back Door: The Best Of Deep Purple in the 80s', artist:'Deep Purple'},
  {title:'Machine Head', artist:'Deep Purple'},
  {title:'Purpendicular', artist:'Deep Purple'},
  {title:'Slaves And Masters', artist:'Deep Purple'},
  {title:'Stormbringer', artist:'Deep Purple'},
  {title:'The Battle Rages On', artist:'Deep Purple'},
  {title:'Vault: Def Leppards Greatest Hits', artist:'Def Leppard'},
  {title:'Outbreak', artist:'Dennis Chambers'},
  {title:'Djavan Ao Vivo - Vol. 02', artist:'Djavan'},
  {title:'Djavan Ao Vivo - Vol. 1', artist:'Djavan'},
  {title:'Elis Regina-Minha História', artist:'Elis Regina'},
  {title:'The Cream Of Clapton', artist:'Eric Clapton'},
  {title:'Unplugged', artist:'Eric Clapton'},
  {title:'Album Of The Year', artist:'Faith No More'},
  {title:'Angel Dust', artist:'Faith No More'},
  {title:'King For A Day Fool For A Lifetime', artist:'Faith No More'},
  {title:'The Real Thing', artist:'Faith No More'},
  {title:'Deixa Entrar', artist:'Falamansa'},
  {title:'In Your Honor [Disc 1]', artist:'Foo Fighters'},
  {title:'In Your Honor [Disc 2]', artist:'Foo Fighters'},
  {title:'One By One', artist:'Foo Fighters'},
  {title:'The Colour And The Shape', artist:'Foo Fighters'},
  {title:'My Way: The Best Of Frank Sinatra [Disc 1]', artist:'Frank Sinatra'},
  {title:'Roda De Funk', artist:'Funk Como Le Gusta'},
  {title:'As Canções de Eu Tu Eles', artist:'Gilberto Gil'},
  {title:'Quanta Gente Veio Ver (Live)', artist:'Gilberto Gil'},
  {title:'Quanta Gente Veio ver--Bônus De Carnaval', artist:'Gilberto Gil'},
  {title:'Faceless', artist:'Godsmack'},
  {title:'American Idiot', artist:'Green Day'},
  {title:'Appetite for Destruction', artist:'Guns N Roses'},
  {title:'Use Your Illusion I', artist:'Guns N Roses'},
  {title:'Use Your Illusion II', artist:'Guns N Roses'},
  {title:'Blue Moods', artist:'Incognito'},
  {title:'A Matter of Life and Death', artist:'Iron Maiden'},
  {title:'A Real Dead One', artist:'Iron Maiden'},
  {title:'A Real Live One', artist:'Iron Maiden'},
  {title:'Brave New World', artist:'Iron Maiden'},
  {title:'Dance Of Death', artist:'Iron Maiden'},
  {title:'Fear Of The Dark', artist:'Iron Maiden'},
  {title:'Iron Maiden', artist:'Iron Maiden'},
  {title:'Killers', artist:'Iron Maiden'},
  {title:'Live After Death', artist:'Iron Maiden'},
  {title:'Live At Donington 1992 (Disc 1)', artist:'Iron Maiden'},
  {title:'Live At Donington 1992 (Disc 2)', artist:'Iron Maiden'},
  {title:'No Prayer For The Dying', artist:'Iron Maiden'},
  {title:'Piece Of Mind', artist:'Iron Maiden'},
  {title:'Powerslave', artist:'Iron Maiden'},
  {title:'Rock In Rio [CD1]', artist:'Iron Maiden'},
  {title:'Rock In Rio [CD2]', artist:'Iron Maiden'},
  {title:'Seventh Son of a Seventh Son', artist:'Iron Maiden'},
  {title:'Somewhere in Time', artist:'Iron Maiden'},
  {title:'The Number of The Beast', artist:'Iron Maiden'},
  {title:'The X Factor', artist:'Iron Maiden'},
  {title:'Virtual XI', artist:'Iron Maiden'},
  {title:'Sex Machine', artist:'James Brown'},
  {title:'Emergency On Planet Earth', artist:'Jamiroquai'},
  {title:'Synkronized', artist:'Jamiroquai'},
  {title:'The Return Of The Space Cowboy', artist:'Jamiroquai'},
  {title:'Get Born', artist:'JET'},
  {title:'Are You Experienced?', artist:'Jimi Hendrix'},
  {title:'Surfing with the Alien (Remastered)', artist:'Joe Satriani'},
  {title:'Jorge Ben Jor 25 Anos', artist:'Jorge Ben'},
  {title:'Jota Quest-1995', artist:'Jota Quest'},
  {title:'Cafezinho', artist:'João Suplicy'},
  {title:'Living After Midnight', artist:'Judas Priest'},
  {title:'Unplugged [Live]', artist:'Kiss'},
  {title:'BBC Sessions [Disc 2] [Live]', artist:'Led Zeppelin'},
  {title:'Coda', artist:'Led Zeppelin'},
  {title:'Houses Of The Holy', artist:'Led Zeppelin'},
  {title:'In Through The Out Door', artist:'Led Zeppelin'},
  {title:'IV', artist:'Led Zeppelin'},
  {title:'Led Zeppelin I', artist:'Led Zeppelin'},
  {title:'Led Zeppelin II', artist:'Led Zeppelin'},
  {title:'Led Zeppelin III', artist:'Led Zeppelin'},
  {title:'Physical Graffiti [Disc 2]', artist:'Led Zeppelin'},
  {title:'Presence', artist:'Led Zeppelin'},
  {title:'The Song Remains The Same (Disc 1)', artist:'Led Zeppelin'},
  {title:'The Song Remains The Same (Disc 2)', artist:'Led Zeppelin'},
  {title:'A TempestadeTempestade Ou O Livro Dos Dias', artist:'Legião Urbana'},
  {title:'Mais Do Mesmo', artist:'Legião Urbana'},
  {title:'Greatest Hits', artist:'Lenny Kravitz'},
  {title:'Lulu Santos - RCA 100 Anos De Música - Álbum 01', artist:'Lulu Santos'},
  {title:'Lulu Santos - RCA 100 Anos De Música - Álbum 02', artist:'Lulu Santos'},
  {title:'Misplaced Childhood', artist:'Marillion'},
  {title:'Barulhinho Bom', artist:'Marisa Monte'},
  {title:'Seek And Shall Find: More Of The Best (1963-1981)', artist:'Marvin Gaye'},
  {title:'The Best Of Men At Work', artist:'Men At Work'},
  {title:'Black Album', artist:'Metallica'},
  {title:'Garage Inc. (Disc 2)', artist:'Metallica'},
  {title:'Kill Em All', artist:'Metallica'},
  {title:'Load', artist:'Metallica'},
  {title:'Master Of Puppets', artist:'Metallica'},
  {title:'ReLoad', artist:'Metallica'},
  {title:'Ride The Lightning', artist:'Metallica'},
  {title:'St. Anger', artist:'Metallica'},
  {title:'...And Justice For All', artist:'Metallica'},
  {title:'Miles Ahead', artist:'Miles Davis'},
  {title:'Milton Nascimento Ao Vivo', artist:'Milton Nascimento'},
  {title:'Minas', artist:'Milton Nascimento'},
  {title:'Ace Of Spades', artist:'Motörhead'},
  {title:'Demorou...', artist:'Mônica Marianno'},
  {title:'Motley Crue Greatest Hits', artist:'Mötley Crüe'},
  {title:'From The Muddy Banks Of The Wishkah [Live]', artist:'Nirvana'},
  {title:'Nevermind', artist:'Nirvana'},
  {title:'Compositores', artist:'O Terço'},
  {title:'Olodum', artist:'Olodum'},
  {title:'Acústico MTV', artist:'Os Paralamas Do Sucesso'},
  {title:'Arquivo II', artist:'Os Paralamas Do Sucesso'},
  {title:'Arquivo Os Paralamas Do Sucesso', artist:'Os Paralamas Do Sucesso'},
  {title:'Bark at the Moon (Remastered)', artist:'Ozzy Osbourne'},
  {title:'Blizzard of Ozz', artist:'Ozzy Osbourne'},
  {title:'Diary of a Madman (Remastered)', artist:'Ozzy Osbourne'},
  {title:'No More Tears (Remastered)', artist:'Ozzy Osbourne'},
  {title:'Tribute', artist:'Ozzy Osbourne'},
  {title:'Walking Into Clarksdale', artist:'Page & Plant'},
  {title:'Original Soundtracks 1', artist:'Passengers'},
  {title:'The Beast Live', artist:'Paul DIanno'},
  {title:'Live On Two Legs [Live]', artist:'Pearl Jam'},
  {title:'Pearl Jam', artist:'Pearl Jam'},
  {title:'Riot Act', artist:'Pearl Jam'},
  {title:'Ten', artist:'Pearl Jam'},
  {title:'Vs.', artist:'Pearl Jam'},
  {title:'Dark Side Of The Moon', artist:'Pink Floyd'},
  {title:'Os Cães Ladram Mas A Caravana Não Pára', artist:'Planet Hemp'},
  {title:'Greatest Hits I', artist:'Queen'},
  {title:'News Of The World', artist:'Queen'},
  {title:'Out Of Time', artist:'R.E.M. Feat. Kate Pearson'},
  {title:'Green', artist:'R.E.M.'},
  {title:'New Adventures In Hi-Fi', artist:'R.E.M.'},
  {title:'The Best Of R.E.M.: The IRS Years', artist:'R.E.M.'},
  {title:'Cesta Básica', artist:'Raimundos'},
  {title:'Raul Seixas', artist:'Raul Seixas'},
  {title:'Blood Sugar Sex Magik', artist:'Red Hot Chili Peppers'},
  {title:'By The Way', artist:'Red Hot Chili Peppers'},
  {title:'Californication', artist:'Red Hot Chili Peppers'},
  {title:'Retrospective I (1974-1980)', artist:'Rush'},
  {title:'Santana - As Years Go By', artist:'Santana'},
  {title:'Santana Live', artist:'Santana'},
  {title:'Maquinarama', artist:'Skank'},
  {title:'O Samba Poconé', artist:'Skank'},
  {title:'Judas 0: B-Sides and Rarities', artist:'Smashing Pumpkins'},
  {title:'Rotten Apples: Greatest Hits', artist:'Smashing Pumpkins'},
  {title:'A-Sides', artist:'Soundgarden'},
  {title:'Morning Dance', artist:'Spyro Gyra'},
  {title:'In Step', artist:'Stevie Ray Vaughan & Double Trouble'},
  {title:'Core', artist:'Stone Temple Pilots'},
  {title:'Mezmerize', artist:'System Of A Down'},
  {title:'[1997] Black Light Syndrome', artist:'Terry Bozzio, Tony Levin & Steve Stevens'},
  {title:'Live [Disc 1]', artist:'The Black Crowes'},
  {title:'Live [Disc 2]', artist:'The Black Crowes'},
  {title:'The Singles', artist:'The Clash'},
  {title:'Beyond Good And Evil', artist:'The Cult'},
  {title:'Pure Cult: The Best Of The Cult (For Rockers, Ravers, Lovers & Sinners) [UK]', artist:'The Cult'},
  {title:'The Doors', artist:'The Doors'},
  {title:'The Police Greatest Hits', artist:'The Police'},
  {title:'Hot Rocks, 1964-1971 (Disc 1)', artist:'The Rolling Stones'},
  {title:'No Security', artist:'The Rolling Stones'},
  {title:'Voodoo Lounge', artist:'The Rolling Stones'},
  {title:'Tangents', artist:'The Tea Party'},
  {title:'Transmission', artist:'The Tea Party'},
  {title:'My Generation - The Very Best Of The Who', artist:'The Who'},
  {title:'Serie Sem Limite (Disc 1)', artist:'Tim Maia'},
  {title:'Serie Sem Limite (Disc 2)', artist:'Tim Maia'},
  {title:'Acústico', artist:'Titãs'},
  {title:'Volume Dois', artist:'Titãs'},
  {title:'Battlestar Galactica: The Story So Far', artist:'Battlestar Galactica'},
  {title:'Battlestar Galactica, Season 3', artist:'Battlestar Galactica'},
  {title:'Heroes, Season 1', artist:'Heroes'},
  {title:'Lost, Season 3', artist:'Lost'},
  {title:'Lost, Season 1', artist:'Lost'},
  {title:'Lost, Season 2', artist:'Lost'},
  {title:'Achtung Baby', artist:'U2'},
  {title:'All That You Cant Leave Behind', artist:'U2'},
  {title:'B-Sides 1980-1990', artist:'U2'},
  {title:'How To Dismantle An Atomic Bomb', artist:'U2'},
  {title:'Pop', artist:'U2'},
  {title:'Rattle And Hum', artist:'U2'},
  {title:'The Best Of 1980-1990', artist:'U2'},
  {title:'War', artist:'U2'},
  {title:'Zooropa', artist:'U2'},
  {title:'UB40 The Best Of - Volume Two [UK]', artist:'UB40'},
  {title:'Diver Down', artist:'Van Halen'},
  {title:'The Best Of Van Halen, Vol. I', artist:'Van Halen'},
  {title:'Van Halen', artist:'Van Halen'},
  {title:'Van Halen III', artist:'Van Halen'},
  {title:'Contraband', artist:'Velvet Revolver'},
  {title:'Vinicius De Moraes', artist:'Vinícius De Moraes'},
  {title:'Ao Vivo [IMPORT]', artist:'Zeca Pagodinho'},
  {title:'The Office, Season 1', artist:'The Office'},
  {title:'The Office, Season 2', artist:'The Office'},
  {title:'The Office, Season 3', artist:'The Office'},
  {title:'Un-Led-Ed', artist:'Dread Zeppelin'},
  {title:'Battlestar Galactica (Classic), Season 1', artist:'Battlestar Galactica (Classic)'},
  {title:'Aquaman', artist:'Aquaman'},
  {title:'Instant Karma: The Amnesty International Campaign to Save Darfur', artist:'U2'},
  {title:'Speak of the Devil', artist:'Ozzy Osbourne'},
  {title:'20th Century Masters - The Millennium Collection: The Best of Scorpions', artist:'Scorpions'},
  {title:'House of Pain', artist:'House Of Pain'},
  {title:'Radio Brasil (O Som da Jovem Vanguarda) - Seleccao de Henrique Amaro', artist:'O Rappa'},
  {title:'Cake: B-Sides and Rarities', artist:'Cake'},
  {title:'LOST, Season 4', artist:'Lost'},
  {title:'Quiet Songs', artist:'Aisha Duo'},
  {title:'Muso Ko', artist:'Habib Koité and Bamada'},
  {title:'Realize', artist:'Karsh Kale'},
  {title:'Every Kind of Light', artist:'The Posies'},
  {title:'Duos II', artist:'Luciana Souza/Romero Lubambo'},
  {title:'Worlds', artist:'Aaron Goldberg'},
  {title:'The Best of Beethoven', artist:'Nicolaus Esterhazy Sinfonia'},
  {title:'Temple of the Dog', artist:'Temple of the Dog'},
  {title:'Carry On', artist:'Chris Cornell'},
  {title:'Revelations', artist:'Audioslave'},
  {title:'Adorate Deum: Gregorian Chant from the Proper of the Mass', artist:'Alberto Turco & Nova Schola Gregoriana'},
  {title:'Allegri: Miserere', artist:'Richard Marlow & The Choir of Trinity College, Cambridge'},
  {title:'Pachelbel: Canon & Gigue', artist:'English Concert & Trevor Pinnock'},
  {title:'Vivaldi: The Four Seasons', artist:'Anne-Sophie Mutter, Herbert Von Karajan & Wiener Philharmoniker'},
  {title:'Bach: Violin Concertos', artist:'Hilary Hahn, Jeffrey Kahane, Los Angeles Chamber Orchestra & Margaret Batjer'},
  {title:'Bach: Goldberg Variations', artist:'Wilhelm Kempff'},
  {title:'Bach: The Cello Suites', artist:'Yo-Yo Ma'},
  {title:'Handel: The Messiah (Highlights)', artist:'Scholars Baroque Ensemble'},
  {title:'The World of Classical Favourites', artist:'Academy of St. Martin in the Fields & Sir Neville Marriner'},
  {title:'Sir Neville Marriner: A Celebration', artist:'Academy of St. Martin in the Fields Chamber Ensemble & Sir Neville Marriner'},
  {title:'Mozart: Wind Concertos', artist:'Berliner Philharmoniker, Claudio Abbado & Sabine Meyer'},
  {title:'Haydn: Symphonies 99 - 104', artist:'Royal Philharmonic Orchestra & Sir Thomas Beecham'},
  {title:'Beethoven: Symhonies Nos. 5 & 6', artist:'Orchestre Révolutionnaire et Romantique & John Eliot Gardiner'},
  {title:'A Soprano Inspired', artist:'Britten Sinfonia, Ivor Bolton & Lesley Garrett'},
  {title:'Great Opera Choruses', artist:'Chicago Symphony Chorus, Chicago Symphony Orchestra & Sir Georg Solti'},
  {title:'Wagner: Favourite Overtures', artist:'Sir Georg Solti & Wiener Philharmoniker'},
  {title:'Fauré: Requiem, Ravel: Pavane & Others', artist:'Academy of St. Martin in the Fields, John Birch, Sir Neville Marriner & Sylvia McNair'},
  {title:'Tchaikovsky: The Nutcracker', artist:'London Symphony Orchestra & Sir Charles Mackerras'},
  {title:'The Last Night of the Proms', artist:'Barry Wordsworth & BBC Concert Orchestra'},
  {title:'Puccini: Madama Butterfly - Highlights', artist:'Herbert Von Karajan, Mirella Freni & Wiener Philharmoniker'},
  {title:'Holst: The Planets, Op. 32 & Vauhan Williams: Fantasies', artist:'Eugene Ormandy'},
  {title:'Pavarottis Opera Made Easy', artist:'Luciano Pavarotti'},
  {title:'Great Performances - Barbers Adagio and Other Romantic Favorites for Strings', artist:'Leonard Bernstein & New York Philharmonic'},
  {title:'Carmina Burana', artist:'Boston Symphony Orchestra & Seiji Ozawa'},
  {title:'A Copland Celebration, Vol. I', artist:'Aaron Copland & London Symphony Orchestra'},
  {title:'Bach: Toccata & Fugue in D Minor', artist:'Ton Koopman'},
  {title:'Prokofiev: Symphony No.1', artist:'Sergei Prokofiev & Yuri Temirkanov'},
  {title:'Scheherazade', artist:'Chicago Symphony Orchestra & Fritz Reiner'},
  {title:'Bach: The Brandenburg Concertos', artist:'Orchestra of The Age of Enlightenment'},
  {title:'Chopin: Piano Concertos Nos. 1 & 2', artist:'Emanuel Ax, Eugene Ormandy & Philadelphia Orchestra'},
  {title:'Mascagni: Cavalleria Rusticana', artist:'James Levine'},
  {title:'Sibelius: Finlandia', artist:'Berliner Philharmoniker & Hans Rosbaud'},
  {title:'Beethoven Piano Sonatas: Moonlight & Pastorale', artist:'Maurizio Pollini'},
  {title:'Great Recordings of the Century - Mahler: Das Lied von der Erde', artist:'Gustav Mahler'},
  {title:'Elgar: Cello Concerto & Vaughan Williams: Fantasias', artist:'Felix Schmidt, London Symphony Orchestra & Rafael Frühbeck de Burgos'},
  {title:'Adams, John: The Chairman Dances', artist:'Edo de Waart & San Francisco Symphony'},
  {title:'Tchaikovsky: 1812 Festival Overture, Op.49, Capriccio Italien & Beethoven: Wellingtons Victory', artist:'Antal Doráti & London Symphony Orchestra'},
  {title:'Palestrina: Missa Papae Marcelli & Allegri: Miserere', artist:'Choir Of Westminster Abbey & Simon Preston'},
  {title:'Prokofiev: Romeo & Juliet', artist:'Michael Tilson Thomas & San Francisco Symphony'},
  {title:'Strauss: Waltzes', artist:'Eugene Ormandy'},
  {title:'Berlioz: Symphonie Fantastique', artist:'Michael Tilson Thomas & San Francisco Symphony'},
  {title:'Bizet: Carmen Highlights', artist:'Chor der Wiener Staatsoper, Herbert Von Karajan & Wiener Philharmoniker'},
  {title:'English Renaissance', artist:'The Kings Singers'},
  {title:'Handel: Music for the Royal Fireworks (Original Version 1749)', artist:'English Concert & Trevor Pinnock'},
  {title:'Grieg: Peer Gynt Suites & Sibelius: Pelléas et Mélisande', artist:'Berliner Philharmoniker & Herbert Von Karajan'},
  {title:'Mozart Gala: Famous Arias', artist:'Sir Georg Solti, Sumi Jo & Wiener Philharmoniker'},
  {title:'SCRIABIN: Vers la flamme', artist:'Christopher ORiley'},
  {title:'Armada: Music from the Courts of England and Spain', artist:'Fretwork'},
  {title:'Mozart: Symphonies Nos. 40 & 41', artist:'Berliner Philharmoniker & Herbert Von Karajan'},
  {title:'Back to Black', artist:'Amy Winehouse'},
  {title:'Frank', artist:'Amy Winehouse'},
  {title:'Carried to Dust (Bonus Track Version)', artist:'Calexico'},
  {title:'Beethoven: Symphony No. 6 Pastoral Etc.', artist:'Otto Klemperer & Philharmonia Orchestra'},
  {title:'Bartok: Violin & Viola Concertos', artist:'Yehudi Menuhin'},
  {title:'Mendelssohn: A Midsummer Nights Dream', artist:'Philharmonia Orchestra & Sir Neville Marriner'},
  {title:'Bach: Orchestral Suites Nos. 1 - 4', artist:'Academy of St. Martin in the Fields, Sir Neville Marriner & Thurston Dart'},
  {title:'Charpentier: Divertissements, Airs & Concerts', artist:'Les Arts Florissants & William Christie'},
  {title:'South American Getaway', artist:'The 12 Cellists of The Berlin Philharmonic'},
  {title:'Górecki: Symphony No. 3', artist:'Adrian Leaper & Doreen de Feis'},
  {title:'Purcell: The Fairy Queen', artist:'Roger Norrington, London Classical Players'},
  {title:'The Ultimate Relexation Album', artist:'Charles Dutoit & LOrchestre Symphonique de Montréal'},
  {title:'Purcell: Music for the Queen Mary', artist:'Equale Brass Ensemble, John Eliot Gardiner & Munich Monteverdi Orchestra and Choir'},
  {title:'Weill: The Seven Deadly Sins', artist:'Kent Nagano and Orchestre de lOpéra de Lyon'},
  {title:'J.S. Bach: Chaconne, Suite in E Minor, Partita in E Major & Prelude, Fugue and Allegro', artist:'Julian Bream'},
  {title:'Prokofiev: Symphony No.5 & Stravinksy: Le Sacre Du Printemps', artist:'Berliner Philharmoniker & Herbert Von Karajan'},
  {title:'Szymanowski: Piano Works, Vol. 1', artist:'Martin Roscoe'},
  {title:'Nielsen: The Six Symphonies', artist:'Göteborgs Symfoniker & Neeme Järvi'},
  {title:'Great Recordings of the Century: Paganinis 24 Caprices', artist:'Itzhak Perlman'},
  {title:'Liszt - 12 Études DExecution Transcendante', artist:'Michele Campanella'},
  {title:'Great Recordings of the Century - Shubert: Schwanengesang, 4 Lieder', artist:'Gerald Moore'},
  {title:'Locatelli: Concertos for Violin, Strings and Continuo, Vol. 3', artist:'Mela Tenenbaum, Pro Musica Prague & Richard Kapp'},
  {title:'Respighi:Pines of Rome', artist:'Eugene Ormandy'},
  {title:'Schubert: The Late String Quartets & String Quintet (3 CDs)', artist:'Emerson String Quartet'},
  {title:'Monteverdi: LOrfeo', artist:'C. Monteverdi, Nigel Rogers - Chiaroscuro; London Baroque; London Cornett & Sackbu'},
  {title:'Mozart: Chamber Music', artist:'Nash Ensemble'},
  {title:'Koyaanisqatsi (Soundtrack from the Motion Picture)', artist:'Philip Glass Ensemble'}
]

# ----------------------------------------------------------
# TABLEAU DES PISTES MUSICALES (extrait représentatif)
# ----------------------------------------------------------
# Ce tableau contient les hashes de toutes les pistes à insérer.
# Chaque hash contient : title, album, artist, duration (ms), size (octets), price ($)
tracks_array = [
  {title:'For Those About To Rock (We Salute You)', album:'For Those About To Rock We Salute You', artist:'AC/DC', duration:343719, size:11170334, price:0.99},
  {title:'Balls to the Wall', album:'Balls to the Wall', artist:'Accept', duration:342562, size:5510424, price:0.99},
  {title:'Fast As a Shark', album:'Restless and Wild', artist:'Accept', duration:230619, size:3990994, price:0.99},
  {title:'Restless and Wild', album:'Restless and Wild', artist:'Accept', duration:252051, size:4331779, price:0.99},
  {title:'Princess of the Dawn', album:'Restless and Wild', artist:'Accept', duration:375418, size:6290521, price:0.99},
  {title:'Put The Finger On You', album:'For Those About To Rock We Salute You', artist:'AC/DC', duration:205662, size:6713451, price:0.99},
  {title:'Lets Get It Up', album:'For Those About To Rock We Salute You', artist:'AC/DC', duration:233926, size:7636561, price:0.99},
  {title:'Inject The Venom', album:'For Those About To Rock We Salute You', artist:'AC/DC', duration:210834, size:6852860, price:0.99},
  {title:'Snowballed', album:'For Those About To Rock We Salute You', artist:'AC/DC', duration:203102, size:6599424, price:0.99},
  {title:'Evil Walks', album:'For Those About To Rock We Salute You', artist:'AC/DC', duration:263497, size:8611245, price:0.99},
  {title:'C.O.D.', album:'For Those About To Rock We Salute You', artist:'AC/DC', duration:199836, size:6566314, price:0.99},
  {title:'Breaking The Rules', album:'For Those About To Rock We Salute You', artist:'AC/DC', duration:263288, size:8596840, price:0.99},
  {title:'Night Of The Long Knives', album:'For Those About To Rock We Salute You', artist:'AC/DC', duration:205688, size:6706347, price:0.99},
  {title:'Spellbound', album:'For Those About To Rock We Salute You', artist:'AC/DC', duration:270863, size:8817038, price:0.99},
  {title:'Go Down', album:'Let There Be Rock', artist:'AC/DC', duration:331180, size:10847611, price:0.99},
  {title:'Dog Eat Dog', album:'Let There Be Rock', artist:'AC/DC', duration:215196, size:7032162, price:0.99},
  {title:'Let There Be Rock', album:'Let There Be Rock', artist:'AC/DC', duration:366654, size:12021261, price:0.99},
  {title:'Bad Boy Boogie', album:'Let There Be Rock', artist:'AC/DC', duration:267728, size:8776140, price:0.99},
  {title:'Problem Child', album:'Let There Be Rock', artist:'AC/DC', duration:325041, size:10617116, price:0.99},
  {title:'Overdose', album:'Let There Be Rock', artist:'AC/DC', duration:369319, size:12066294, price:0.99},
  {title:'Hell Aint A Bad Place To Be', album:'Let There Be Rock', artist:'AC/DC', duration:254380, size:8331286, price:0.99},
  {title:'Whole Lotta Rosie', album:'Let There Be Rock', artist:'AC/DC', duration:323761, size:10547154, price:0.99},
  {title:'Walk On Water', album:'Big Ones', artist:'Aerosmith', duration:295680, size:9719579, price:0.99},
  {title:'Love In An Elevator', album:'Big Ones', artist:'Aerosmith', duration:321828, size:10552051, price:0.99},
  {title:'Rag Doll', album:'Big Ones', artist:'Aerosmith', duration:264698, size:8675345, price:0.99},
  {title:'What It Takes', album:'Big Ones', artist:'Aerosmith', duration:310622, size:10144730, price:0.99},
  {title:'Dude (Looks Like A Lady)', album:'Big Ones', artist:'Aerosmith', duration:264855, size:8679940, price:0.99},
  {title:'Janies Got A Gun', album:'Big Ones', artist:'Aerosmith', duration:330736, size:10869391, price:0.99},
  {title:'Cryin', album:'Big Ones', artist:'Aerosmith', duration:309263, size:10056995, price:0.99},
  {title:'Amazing', album:'Big Ones', artist:'Aerosmith', duration:356519, size:11616195, price:0.99},
  {title:'All I Really Want', album:'Jagged Little Pill', artist:'Alanis Morissette', duration:284891, size:9375567, price:0.99},
  {title:'You Oughta Know', album:'Jagged Little Pill', artist:'Alanis Morissette', duration:249234, size:8196916, price:0.99},
  {title:'Perfect', album:'Jagged Little Pill', artist:'Alanis Morissette', duration:188133, size:6145404, price:0.99},
  {title:'Hand In My Pocket', album:'Jagged Little Pill', artist:'Alanis Morissette', duration:221570, size:7224246, price:0.99},
  {title:'Right Through You', album:'Jagged Little Pill', artist:'Alanis Morissette', duration:176117, size:5793082, price:0.99},
  {title:'Forgiven', album:'Jagged Little Pill', artist:'Alanis Morissette', duration:300355, size:9753256, price:0.99},
  {title:'You Learn', album:'Jagged Little Pill', artist:'Alanis Morissette', duration:239699, size:7824837, price:0.99},
  {title:'Head Over Feet', album:'Jagged Little Pill', artist:'Alanis Morissette', duration:267493, size:8758008, price:0.99},
  {title:'Mary Jane', album:'Jagged Little Pill', artist:'Alanis Morissette', duration:280607, size:9163588, price:0.99},
  {title:'Ironic', album:'Jagged Little Pill', artist:'Alanis Morissette', duration:229825, size:7598866, price:0.99},
  {title:'Not The Doctor', album:'Jagged Little Pill', artist:'Alanis Morissette', duration:227631, size:7604601, price:0.99},
  {title:'Wake Up', album:'Jagged Little Pill', artist:'Alanis Morissette', duration:293485, size:9703359, price:0.99},
  {title:'We Die Young', album:'Facelift', artist:'Alice In Chains', duration:152084, size:4925362, price:0.99},
  {title:'Man In The Box', album:'Facelift', artist:'Alice In Chains', duration:286641, size:9310272, price:0.99},
  {title:'Sea Of Sorrow', album:'Facelift', artist:'Alice In Chains', duration:349831, size:11316328, price:0.99},
  {title:'Bleed The Freak', album:'Facelift', artist:'Alice In Chains', duration:241946, size:7847716, price:0.99},
  {title:'Love, Hate, Love', album:'Facelift', artist:'Alice In Chains', duration:387134, size:12575396, price:0.99},
  {title:'Sunshine', album:'Facelift', artist:'Alice In Chains', duration:284969, size:9216057, price:0.99},
  {title:'Enter Sandman', album:'Plays Metallica By Four Cellos', artist:'Apocalyptica', duration:221701, size:7286305, price:0.99},
  {title:'Master Of Puppets', album:'Plays Metallica By Four Cellos', artist:'Apocalyptica', duration:436453, size:14375310, price:0.99},
  {title:'Cochise', album:'Audioslave', artist:'Audioslave', duration:222380, size:5339931, price:0.99},
  {title:'Show Me How to Live', album:'Audioslave', artist:'Audioslave', duration:277890, size:6672176, price:0.99},
  {title:'Like a Stone', album:'Audioslave', artist:'Audioslave', duration:294034, size:7059624, price:0.99},
  {title:'Your Time Has Come', album:'Out Of Exile', artist:'Audioslave', duration:255529, size:8273592, price:0.99},
  {title:'Out Of Exile', album:'Out Of Exile', artist:'Audioslave', duration:291291, size:9506571, price:0.99},
  {title:'Be Yourself', album:'Out Of Exile', artist:'Audioslave', duration:279484, size:9106160, price:0.99},
  {title:'Money', album:'BackBeat Soundtrack', artist:'BackBeat', duration:147591, size:2365897, price:0.99},
  {title:'Long Tall Sally', album:'BackBeat Soundtrack', artist:'BackBeat', duration:106396, size:1707084, price:0.99},
  {title:'Bad Boy', album:'BackBeat Soundtrack', artist:'BackBeat', duration:116088, size:1862126, price:0.99},
  {title:'Burn', album:'MK III The Final Concerts [Disc 1]', artist:'Deep Purple', duration:453955, size:14775708, price:0.99},
  {title:'Stormbringer', album:'MK III The Final Concerts [Disc 1]', artist:'Deep Purple', duration:277133, size:9050022, price:0.99},
  {title:'Smoke On The Water', album:'MK III The Final Concerts [Disc 1]', artist:'Deep Purple', duration:618031, size:20103125, price:0.99},
  {title:'(Da Le) Yaleo', album:'Supernatural', artist:'Santana', duration:353488, size:11769507, price:0.99},
  {title:'Smooth', album:'Supernatural', artist:'Santana', duration:298161, size:9867455, price:0.99},
  {title:'Maria Maria', album:'Supernatural', artist:'Santana', duration:262635, size:8664601, price:0.99},
  {title:'Nows The Time', album:'The Essential Miles Davis [Disc 1]', artist:'Miles Davis', duration:197459, size:6358868, price:0.99},
  {title:'So What', album:'The Essential Miles Davis [Disc 1]', artist:'Miles Davis', duration:564009, size:18360449, price:0.99},
  {title:'Space Truckin', album:'The Final Concerts (Disc 2)', artist:'Deep Purple', duration:1196094, size:39267613, price:0.99},
  {title:'Susie Q', album:'Chronicle, Vol. 1', artist:'Creedence Clearwater Revival', duration:275565, size:9043825, price:0.99},
  {title:'Proud Mary', album:'Chronicle, Vol. 1', artist:'Creedence Clearwater Revival', duration:189022, size:6229590, price:0.99},
  {title:'Bad Moon Rising', album:'Chronicle, Vol. 1', artist:'Creedence Clearwater Revival', duration:140146, size:4609835, price:0.99},
  {title:'Fortunate Son', album:'Chronicle, Vol. 1', artist:'Creedence Clearwater Revival', duration:140329, size:4617559, price:0.99},
  {title:'Layla', album:'The Cream Of Clapton', artist:'Eric Clapton', duration:430733, size:14115792, price:0.99},
  {title:'Sunshine Of Your Love', album:'The Cream Of Clapton', artist:'Eric Clapton', duration:252891, size:8225889, price:0.99},
  {title:'White Room', album:'The Cream Of Clapton', artist:'Eric Clapton', duration:301583, size:9872606, price:0.99},
  {title:'Cocaine', album:'The Cream Of Clapton', artist:'Eric Clapton', duration:215928, size:7138399, price:0.99},
  {title:'I Shot The Sheriff', album:'The Cream Of Clapton', artist:'Eric Clapton', duration:263862, size:8738973, price:0.99},
  {title:'Wonderful Tonight', album:'The Cream Of Clapton', artist:'Eric Clapton', duration:221387, size:7326923, price:0.99},
  {title:'Signe', album:'Unplugged', artist:'Eric Clapton', duration:193515, size:6475042, price:0.99},
  {title:'Tears In Heaven', album:'Unplugged', artist:'Eric Clapton', duration:274729, size:9032835, price:0.99},
  {title:'Layla', album:'Unplugged', artist:'Eric Clapton', duration:285387, size:9490542, price:0.99},
  {title:'Rollin And Tumblin', album:'Unplugged', artist:'Eric Clapton', duration:251768, size:8407355, price:0.99},
  {title:'Highway Star', album:'Machine Head', artist:'Deep Purple', duration:368770, size:12012452, price:0.99},
  {title:'Smoke On The Water', album:'Machine Head', artist:'Deep Purple', duration:340871, size:11246496, price:0.99},
  {title:'Space Truckin', album:'Machine Head', artist:'Deep Purple', duration:272796, size:8981030, price:0.99},
  {title:'Land Of Sunshine', album:'Angel Dust', artist:'Faith No More', duration:223921, size:7353567, price:0.99},
  {title:'Midlife Crisis', album:'Angel Dust', artist:'Faith No More', duration:263235, size:8628841, price:0.99},
  {title:'A Small Victory', album:'Angel Dust', artist:'Faith No More', duration:297168, size:9733572, price:0.99},
  {title:'Pour Some Sugar On Me', album:'Vault: Def Leppards Greatest Hits', artist:'Def Leppard', duration:292519, size:9518842, price:0.99},
  {title:'Love Bites', album:'Vault: Def Leppards Greatest Hits', artist:'Def Leppard', duration:346853, size:11305791, price:0.99},
  {title:'Animal', album:'Vault: Def Leppards Greatest Hits', artist:'Def Leppard', duration:244741, size:7985133, price:0.99},
  {title:'Hysteria', album:'Vault: Def Leppards Greatest Hits', artist:'Def Leppard', duration:355056, size:11622738, price:0.99},
  {title:'Enter Sandman', album:'Black Album', artist:'Metallica', duration:391136, size:12321965, price:0.99},
  {title:'Sad But True', album:'Black Album', artist:'Metallica', duration:324219, size:10551398, price:0.99},
  {title:'Nothing Else Matters', album:'Black Album', artist:'Metallica', duration:387131, size:12600233, price:0.99},
  {title:'Dark Side Of The Moon', album:'Dark Side Of The Moon', artist:'Pink Floyd', duration:162810, size:5339931, price:0.99}
]

# ----------------------------------------------------------
# INSERTION DES ALBUMS EN BASE DE DONNÉES
# ----------------------------------------------------------
# Itère sur chaque hash du tableau et crée un album en BDD.
# each_with_index permet d'afficher la progression dans le terminal.
album_array.each_with_index do |album, index|
  # Crée l'album en BDD à partir du hash (title, artist)
  Album.create(album)
  # Affiche la progression dans le terminal (tous les 50 albums)
  puts "#{index + 1} albums créés..." if (index + 1) % 50 == 0
end

# Message de confirmation pour les albums
puts "==> #{Album.count} albums créés avec succès !"

# ----------------------------------------------------------
# INSERTION DES PISTES EN BASE DE DONNÉES
# ----------------------------------------------------------
# Itère sur chaque hash du tableau et crée une piste en BDD.
tracks_array.each_with_index do |track, index|
  # Crée la piste en BDD à partir du hash (title, album, artist, duration, size, price)
  Track.create(track)
  # Affiche la progression dans le terminal (toutes les 50 pistes)
  puts "#{index + 1} pistes créées..." if (index + 1) % 50 == 0
end

# Message de confirmation pour les pistes
puts "==> #{Track.count} pistes créées avec succès !"
puts "==> Seed Fouta Music terminé. BDD prête !"
